# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clock.xdc

# XDC: new/pin.xdc

# IP: ip/cpuclk/cpuclk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpuclk || ORIG_REF_NAME==cpuclk} -quiet] -quiet
